FROM ubuntu

WORKDIR /app

RUN apt-get update && apt-get install -y python3-pip
RUN apt-get install python3-tk


RUN pip3 install numpy
RUN pip install tkinter


COPY grafos /archivosAPP/grafos/
COPY main.py /archivosAPP/
COPY Grafo.py /archivosAPP/
COPY LectorDeGrafos.py /archivosAPP/
COPY GUI.py /archivosAPP/

WORKDIR /app/archivosAPP/
RUN python3 main.py
